/**
   \file gtk-insteonedit/interface.h
   \author Tim Rightnour
   \brief Insterface prototypes
*/
/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1(void);
GtkWidget* create_dialog1(void);
GtkWidget* create_aboutdialog1(void);
