/*
 * Copyright (c) 2015
 *      Tim Rightnour.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of Tim Rightnour may not be used to endorse or promote 
 *    products derived from this software without specific prior written 
 *    permission.
 *
 * THIS SOFTWARE IS PROVIDED BY TIM RIGHTNOUR ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL TIM RIGHTNOUR BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/**
   \file interface.c
   \brief Widget handling code for gtk-insteonedit
   \author Tim Rightnour
   Initially generated by glade-2
*/

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <sys/queue.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "gnhast.h"
#include "common.h"
#include "confuse.h"
#include "confparser.h"
#include "gncoll.h"
#include "collcmd.h"
#include "insteon.h"
#include "gtk-insteonedit.h"

#include "callbacks.h"
#include "interface.h"
#include "support.h"

extern TAILQ_HEAD(, _device_t) alldevs;
extern TAILQ_HEAD(, _device_group_t) allgroups;
extern GtkWidget *main_window;
extern name_map_t devtype_map[];
extern insteon_devdata_t plminfo;
extern aldb_t *plmaldb;
extern int nrofplmaldb;

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkTreeModel *devicelist_model = NULL;
GtkTreeModel *aldb_model = NULL;
GtkTreeSelection *devicelist_select;
int working = 0;
int getinfo_working = 0;
int getld_working = 0;
GtkIconTheme *icon_theme;
GdkPixbuf *edit_icon, *delete_icon;

/**
   \brief Build the list view model
*/

static GtkTreeModel *create_listview_model(void)
{
	GtkListStore *list;

	list = gtk_list_store_new(LIST_NUM_COLS, G_TYPE_STRING);
	return GTK_TREE_MODEL(list);
}

static GtkTreeModel *create_aldb_model(void)
{
	GtkListStore *list;

	list = gtk_list_store_new(ALDB_NUM_COLS,
				  G_TYPE_STRING,
				  G_TYPE_STRING,
				  G_TYPE_STRING,
				  G_TYPE_STRING,
				  G_TYPE_STRING,
				  G_TYPE_STRING,
				  G_TYPE_STRING,
				  GDK_TYPE_PIXBUF,
				  GDK_TYPE_PIXBUF);
	return GTK_TREE_MODEL(list);
}

/**
   \brief Setup the list view
*/

static void setup_list_view(GtkWidget *treeview)
{
	GtkCellRenderer *renderer;
	GtkTreeViewColumn *col;

	renderer = gtk_cell_renderer_text_new();
	col = gtk_tree_view_column_new_with_attributes(
		"Device", renderer, "text", LIST_UID_COL, NULL);
	gtk_tree_view_append_column(GTK_TREE_VIEW(treeview), col);
}

/**
   \brief Setup the aldb view
*/

static void setup_aldb_view(GtkWidget *treeview)
{
	GtkCellRenderer *renderer;
	GtkTreeViewColumn *col;

	renderer = gtk_cell_renderer_text_new();
	col = gtk_tree_view_column_new_with_attributes(
		"Group #", renderer, "text", GROUP_COL, NULL);
	gtk_tree_view_append_column(GTK_TREE_VIEW(treeview), col);

	renderer = gtk_cell_renderer_text_new();
	col = gtk_tree_view_column_new_with_attributes(
		"Device ID", renderer, "text", DEVID_COL, NULL);
	gtk_tree_view_append_column(GTK_TREE_VIEW(treeview), col);

	renderer = gtk_cell_renderer_text_new();
	col = gtk_tree_view_column_new_with_attributes(
		"Link Data 1", renderer, "text", LD1_COL, NULL);
	gtk_tree_view_append_column(GTK_TREE_VIEW(treeview), col);

	renderer = gtk_cell_renderer_text_new();
	col = gtk_tree_view_column_new_with_attributes(
		"Link Data 2", renderer, "text", LD2_COL, NULL);
	gtk_tree_view_append_column(GTK_TREE_VIEW(treeview), col);

	renderer = gtk_cell_renderer_text_new();
	col = gtk_tree_view_column_new_with_attributes(
		"Link Data 3", renderer, "text", LD3_COL, NULL);
	gtk_tree_view_append_column(GTK_TREE_VIEW(treeview), col);

	renderer = gtk_cell_renderer_text_new();
	col = gtk_tree_view_column_new_with_attributes(
		"In Use", renderer, "text", INUSE_COL, NULL);
	gtk_tree_view_append_column(GTK_TREE_VIEW(treeview), col);

	renderer = gtk_cell_renderer_text_new();
	col = gtk_tree_view_column_new_with_attributes(
		"Master", renderer, "text", MASTER_COL, NULL);
	gtk_tree_view_append_column(GTK_TREE_VIEW(treeview), col);

	renderer = gtk_cell_renderer_pixbuf_new();
	col = gtk_tree_view_column_new_with_attributes(
		"Edit", renderer, "pixbuf", EDIT_COL, NULL);
	gtk_tree_view_append_column(GTK_TREE_VIEW(treeview), col);

	renderer = gtk_cell_renderer_pixbuf_new();
	col = gtk_tree_view_column_new_with_attributes(
		"Delete", renderer, "pixbuf", DELETE_COL, NULL);
	gtk_tree_view_append_column(GTK_TREE_VIEW(treeview), col);
}

/**
   \brief Find the model/iter pair in the list view by uid
   \param model pointer to model
   \param iter pointer to iter
   \param devuid the uid to find
   \param widgetname the widget to find, by name
   \return TRUE if found, FALSE if not
*/

gboolean find_listview_iter_byuid(GtkTreeModel **model, GtkTreeIter *iter,
				  char *devuid, char *widgetname)
{
	GtkWidget *widget;
	char *uid;
	gboolean valid;

	widget = lookup_widget(main_window, widgetname);
	if (widget == NULL || devuid == NULL)
		return FALSE;

	if (GTK_IS_TREE_VIEW(widget)) {
		*model = gtk_tree_view_get_model(GTK_TREE_VIEW(widget));
	} else {
		*model = gtk_icon_view_get_model(GTK_ICON_VIEW(widget));
	}
	if (*model == NULL)
		return FALSE;

	valid = gtk_tree_model_get_iter_first(*model, iter);
	while (valid) {
		gtk_tree_model_get(*model, iter, LIST_UID_COL, &uid, -1);
		if (uid != NULL && strlen(uid) == strlen(devuid) &&
		    strcmp(uid, devuid) == 0) {
			g_free(uid);
			return TRUE;
		} else
			g_free(uid);
		valid = gtk_tree_model_iter_next(*model, iter);
	}

	return FALSE;
}

/**
   \brief Update device list model with device data
   \param dev device to add
   \param model model to add to
   \param level tree item to add to
   \param widgetname the widget name to add to
*/

static void add_device_devicelist_model(device_t *dev,
					GtkTreeModel *model,
					GtkTreeIter *level, char *widgetname)
{
	GtkTreeModel *tmodel;
	GtkTreeIter titer;

	/* check if item exists */
	if (find_listview_iter_byuid(&tmodel, &titer, dev->uid, widgetname))
		return;

	gtk_list_store_append(GTK_LIST_STORE(model), level);
	gtk_list_store_set(GTK_LIST_STORE(model), level, LIST_UID_COL,
			   dev->uid, -1);
}

/**
   \brief Add the PLM to the devicelist
*/

void add_plm_devicelist_model(GtkTreeModel *model)
{
	GtkTreeModel *tmodel;
	GtkTreeIter titer;
	char im[16];

	addr_to_string(im, plminfo.daddr);

	/* check if item exists */
	if (find_listview_iter_byuid(&tmodel, &titer, im, "devicelist"))
		return;

	gtk_list_store_prepend(GTK_LIST_STORE(model), &titer);
	gtk_list_store_set(GTK_LIST_STORE(model), &titer, LIST_UID_COL,
			   im, -1);
}

/**
   \brief update the devicelist_model with the contents of the device tree
*/

void update_devicelist_model(GtkTreeModel *model)
{
	device_t *dev;
	GtkTreeIter item;

	/* now all devices */
	TAILQ_FOREACH(dev, &alldevs, next_all) {
		printf("add device %s\n", dev->uid);
		add_device_devicelist_model(dev, model, &item, "devicelist");
	}
}

/**
   \brief Clear info and link fields
   \param buf buffer to place in info area
*/

void clear_info_link(gchar *buf)
{
	gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window,
						   "entry_devcat")), buf);
	gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window,
						   "entry_devsubcat")), buf);
	gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window,
						   "entry_devfw")), buf);
	gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window,
						   "entry_proto")), buf);
	gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window,
						   "entry_led")), buf);
	gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window,
						   "entry_ramp")), buf);
}

/**
   \brief Update the details window with device info
   \param dev device to update data with
*/

void update_detail_dev(device_t *dev)
{
	if (dev == NULL)
		return;

	gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window, "entry_uid")),
			   dev->uid);
	gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window, "entry_name")),
			   dev->name);
	gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window, "entry_id")),
			   dev->loc);
	gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window,
						   "entry_devtype")),
			   devtype_map[dev->type].name);
}

/**
   \brief Update the details window with plm info
*/

void update_detail_plm(void)
{
	char im[16];

	addr_to_string(im, plminfo.daddr);

	gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window, "entry_uid")),
			   im);
	gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window, "entry_name")),
			   "Insteon PLM");
	gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window, "entry_id")),
			   im);
	gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window,
						   "entry_devtype")),
			   "Hub/Modem");
}

/**
   \brief Update the info window with data
   \param dev device, if NULL, plm
*/

void update_info_dev(device_t *dev)
{
	insteon_devdata_t *dd;
	char buf[256];

	if (dev == NULL) {
		/* assume we are talking about the PLM */
		sprintf(buf, "0x%0.2X", plminfo.devcat);
		gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window,
							   "entry_devcat")),
				   buf);
		sprintf(buf, "0x%0.2X", plminfo.subcat);
		gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window,
							   "entry_devsubcat")),
				   buf);
		sprintf(buf, "0x%0.2X", plminfo.firmware);
		gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window,
							   "entry_devfw")),
				   buf);
		gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window,
							   "entry_proto")),
				   "N/A");
		gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window,
							   "entry_led")),
				   "N/A");
		gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window,
							   "entry_ramp")),
				   "N/A");
		return;
	}

	/* it's a device, do what we can */
	dd = (insteon_devdata_t *)dev->localdata;

	sprintf(buf, "0x%0.2X", dd->devcat);
	gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window,
						   "entry_devcat")), buf);
	sprintf(buf, "0x%0.2X", dd->subcat);
	gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window,
						   "entry_devsubcat")), buf);
	sprintf(buf, "0x%0.2X", dd->firmware);
	gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window,
						   "entry_devfw")), buf);
	sprintf(buf, "0x%0.2X", dd->proto);
	gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window,
						   "entry_proto")), buf);
	sprintf(buf, "0x%0.2X", dd->ramprate);
	gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window,
						   "entry_led")), buf);
	sprintf(buf, "0x%0.2X", dd->ledbright);
	gtk_entry_set_text(GTK_ENTRY(lookup_widget(main_window,
						   "entry_ramp")), buf);

}

/**
   \brief Load the aldb model with data
   \param dev device to load, NULL if plm
*/
void update_aldb_devicelist_model(device_t *dev)
{
	GtkTreeIter iter;
	int i;
	char group[8], devid[16], ld1[8], ld2[8], ld3[8];

	/* nuke the existing data, if any */
	if (gtk_tree_model_get_iter_first(aldb_model, &iter)) {
		while (gtk_list_store_remove(GTK_LIST_STORE(aldb_model),
					     &iter)) {
			;;
		}
	}

	/* invalidate iter */
	(void)gtk_tree_model_get_iter_first(aldb_model, &iter);

	if (dev == NULL) {
		/* we have a PLM */
		for (i=0; i < nrofplmaldb; i++) {
			sprintf(group, "%d", plmaldb[i].group);
			addr_to_string(devid, plmaldb[i].devaddr);
			sprintf(ld1, "0x%0.2X", plmaldb[i].ldata1);
			sprintf(ld2, "0x%0.2X", plmaldb[i].ldata2);
			sprintf(ld3, "0x%0.2X", plmaldb[i].ldata3);
			gtk_list_store_append(GTK_LIST_STORE(aldb_model),
					      &iter);
			gtk_list_store_set(GTK_LIST_STORE(aldb_model), &iter,
					   GROUP_COL, group,
					   DEVID_COL, devid,
					   LD1_COL, ld1,
					   LD2_COL, ld2,
					   LD3_COL, ld3,
					   INUSE_COL, ALINK_IS_USED(plmaldb[i].lflags) ? "YES" : "NO",
					   MASTER_COL, ALINK_IS_MASTER(plmaldb[i].lflags) ? "YES" : "NO",
					   EDIT_COL, edit_icon,
					   DELETE_COL, delete_icon, -1);
		}
	}
	return; /*XXX*/
}


GtkWidget* create_window1 (void)
{
	GtkWidget *window1;
	GtkWidget *vbox1;

	GtkWidget *menubar1;
	GtkWidget *menuitem4;
	GtkWidget *menu4;
	GtkWidget *new1;
	GtkWidget *open1;
	GtkWidget *save1;
	GtkWidget *save_as1;
	GtkWidget *separatormenuitem1;
	GtkWidget *quit1;
	GtkWidget *menuitem5;
	GtkWidget *menu5;
	GtkWidget *cut1;
	GtkWidget *copy1;
	GtkWidget *paste1;
	GtkWidget *delete1;
	GtkWidget *menuitem6;
	GtkWidget *menu6;
	GtkWidget *menuitem7;
	GtkWidget *menu7;
	GtkWidget *about1;
	GtkWidget *hbox1;

	GtkWidget *scrolledwindow1;
	GtkWidget *devicelist;

	GtkWidget *table1;

	GtkWidget *label1, *label2, *label3, *label4, *label5;
	GtkWidget *label6, *label7, *label8, *label9, *label10;

	GtkWidget *entry_led, *entry_ramp, *entry_uid;
	GtkWidget *entry_name, *entry_id, *entry_devtype;
	GtkWidget *entry_devcat, *entry_devsubcat, *entry_devfw;
	GtkWidget *entry_proto;

	GtkWidget *button_get_ld;
	GtkWidget *button_getinfo;

	GtkWidget *scrolledwindow2;
	GtkWidget *aldblist;
	GtkWidget *viewport;
	GtkRequisition size;

	GtkWidget *spinner;

	GtkWidget *button_led_edit;
	GtkWidget *alignment1;
	GtkWidget *hbox3;
	GtkWidget *image1;
	GtkWidget *label25;
	GtkWidget *button_ramp_edit;
	GtkWidget *alignment3;
	GtkWidget *hbox5;
	GtkWidget *image3;
	GtkWidget *label27;
	GtkAccelGroup *accel_group;

	accel_group = gtk_accel_group_new();

	window1 = gtk_window_new(GTK_WINDOW_TOPLEVEL);
	gtk_window_set_title(GTK_WINDOW(window1), _("window1"));
	GLADE_HOOKUP_OBJECT_NO_REF(window1, window1, "window1");

	/* Load in the icon theme and required pixbufs */

	icon_theme = gtk_icon_theme_get_default();
	edit_icon = gtk_icon_theme_load_icon(icon_theme, "edit-select-all",
					     32, 0, NULL);
	delete_icon = gtk_icon_theme_load_icon(icon_theme, "edit-delete",
					     32, 0, NULL);

	/* Main Menu Vbox and main box */
	vbox1 = gtk_vbox_new(FALSE, 0);
	gtk_widget_show(vbox1);
	gtk_container_add(GTK_CONTAINER(window1), vbox1);
	GLADE_HOOKUP_OBJECT(window1, vbox1, "vbox1");

	/* Main Menu */
	menubar1 = gtk_menu_bar_new();
	gtk_widget_show(menubar1);
	gtk_box_pack_start(GTK_BOX(vbox1), menubar1, FALSE, FALSE, 0);
	GLADE_HOOKUP_OBJECT(window1, menubar1, "menubar1");

	menuitem4 = gtk_menu_item_new_with_mnemonic(_("_File"));
	gtk_widget_show(menuitem4);
	gtk_container_add(GTK_CONTAINER(menubar1), menuitem4);
	GLADE_HOOKUP_OBJECT(window1, menuitem4, "menuitem4");

	menu4 = gtk_menu_new();
	gtk_menu_item_set_submenu(GTK_MENU_ITEM(menuitem4), menu4);
	GLADE_HOOKUP_OBJECT(window1, menu4, "menu4");

	new1 = gtk_image_menu_item_new_from_stock("gtk-new", accel_group);
	gtk_widget_show(new1);
	gtk_container_add(GTK_CONTAINER(menu4), new1);
	GLADE_HOOKUP_OBJECT(window1, new1, "new1");

	open1 = gtk_image_menu_item_new_from_stock("gtk-open", accel_group);
	gtk_widget_show(open1);
	gtk_container_add(GTK_CONTAINER(menu4), open1);
	GLADE_HOOKUP_OBJECT(window1, open1, "open1");

	save1 = gtk_image_menu_item_new_from_stock("gtk-save", accel_group);
	gtk_widget_show(save1);
	gtk_container_add(GTK_CONTAINER(menu4), save1);
	GLADE_HOOKUP_OBJECT(window1, save1, "save1");

	save_as1 = gtk_image_menu_item_new_from_stock("gtk-save-as", accel_group);
	gtk_widget_show(save_as1);
	gtk_container_add(GTK_CONTAINER(menu4), save_as1);
	GLADE_HOOKUP_OBJECT(window1, save_as1, "save_as1");

	separatormenuitem1 = gtk_separator_menu_item_new();
	gtk_widget_show(separatormenuitem1);
	gtk_container_add(GTK_CONTAINER(menu4), separatormenuitem1);
	gtk_widget_set_sensitive(separatormenuitem1, FALSE);
	GLADE_HOOKUP_OBJECT(window1, separatormenuitem1, "separatormenuitem1");

	quit1 = gtk_image_menu_item_new_from_stock("gtk-quit", accel_group);
	gtk_widget_show(quit1);
	gtk_container_add(GTK_CONTAINER(menu4), quit1);
	GLADE_HOOKUP_OBJECT(window1, quit1, "quit1");

	menuitem5 = gtk_menu_item_new_with_mnemonic(_("_Edit"));
	gtk_widget_show(menuitem5);
	gtk_container_add(GTK_CONTAINER(menubar1), menuitem5);
	GLADE_HOOKUP_OBJECT(window1, menuitem5, "menuitem5");

	menu5 = gtk_menu_new();
	gtk_menu_item_set_submenu(GTK_MENU_ITEM(menuitem5), menu5);
	GLADE_HOOKUP_OBJECT(window1, menu5, "menu5");

	cut1 = gtk_image_menu_item_new_from_stock("gtk-cut", accel_group);
	gtk_widget_show(cut1);
	gtk_container_add(GTK_CONTAINER(menu5), cut1);
	GLADE_HOOKUP_OBJECT(window1, cut1, "cut1");

	copy1 = gtk_image_menu_item_new_from_stock("gtk-copy", accel_group);
	gtk_widget_show(copy1);
	gtk_container_add(GTK_CONTAINER(menu5), copy1);
	GLADE_HOOKUP_OBJECT(window1, copy1, "copy1");

	paste1 = gtk_image_menu_item_new_from_stock("gtk-paste", accel_group);
	gtk_widget_show(paste1);
	gtk_container_add(GTK_CONTAINER(menu5), paste1);
	GLADE_HOOKUP_OBJECT(window1, paste1, "paste1");

	delete1 = gtk_image_menu_item_new_from_stock("gtk-delete", accel_group);
	gtk_widget_show(delete1);
	gtk_container_add(GTK_CONTAINER(menu5), delete1);
	GLADE_HOOKUP_OBJECT(window1, delete1, "delete1");

	menuitem6 = gtk_menu_item_new_with_mnemonic(_("_View"));
	gtk_widget_show(menuitem6);
	gtk_container_add(GTK_CONTAINER(menubar1), menuitem6);
	GLADE_HOOKUP_OBJECT(window1, menuitem6, "menuitem6");

	menu6 = gtk_menu_new();
	gtk_menu_item_set_submenu(GTK_MENU_ITEM(menuitem6), menu6);
	GLADE_HOOKUP_OBJECT(window1, menu6, "menu6");

	menuitem7 = gtk_menu_item_new_with_mnemonic(_("_Help"));
	gtk_widget_show(menuitem7);
	gtk_container_add(GTK_CONTAINER(menubar1), menuitem7);
	GLADE_HOOKUP_OBJECT(window1, menuitem7, "menuitem7");

	menu7 = gtk_menu_new();
	gtk_menu_item_set_submenu(GTK_MENU_ITEM(menuitem7), menu7);
	GLADE_HOOKUP_OBJECT(window1, menu7, "menu7");

	about1 = gtk_menu_item_new_with_mnemonic(_("_About"));
	gtk_widget_show(about1);
	gtk_container_add(GTK_CONTAINER(menu7), about1);
	GLADE_HOOKUP_OBJECT(window1, about1, "about1");

	/* End Menu */

	hbox1 = gtk_hbox_new(FALSE, 0);
	gtk_widget_show(hbox1);
	gtk_box_pack_start(GTK_BOX(vbox1), hbox1, TRUE, TRUE, 0);
	GLADE_HOOKUP_OBJECT(window1, hbox1, "hbox1");

	scrolledwindow1 = gtk_scrolled_window_new(NULL, NULL);
	gtk_widget_show(scrolledwindow1);
	gtk_box_pack_start(GTK_BOX(hbox1), scrolledwindow1, TRUE, TRUE, 0);
	gtk_scrolled_window_set_shadow_type(GTK_SCROLLED_WINDOW(scrolledwindow1), GTK_SHADOW_IN);
	GLADE_HOOKUP_OBJECT(window1, scrolledwindow1, "scrolledwindow1");


	/* Build the main device list */
	devicelist_model = create_listview_model();
	devicelist = gtk_tree_view_new();
	setup_list_view(devicelist);
	gtk_tree_view_set_model(GTK_TREE_VIEW(devicelist),
				GTK_TREE_MODEL(devicelist_model));
	gtk_widget_show(devicelist);
	GLADE_HOOKUP_OBJECT(window1, devicelist, "devicelist");
	gtk_container_add(GTK_CONTAINER(scrolledwindow1), devicelist);

	devicelist_select = gtk_tree_view_get_selection(GTK_TREE_VIEW(devicelist));
	g_signal_connect(devicelist_select, "changed",
			 G_CALLBACK(dd_listitem_selected), NULL);


	/* Table for right side of screen */
	table1 = gtk_table_new(13, 3, FALSE);
	gtk_widget_show(table1);
	gtk_box_pack_start(GTK_BOX(hbox1), table1, TRUE, TRUE, 0);
	gtk_table_set_row_spacings(GTK_TABLE(table1), 2);
	gtk_table_set_col_spacings(GTK_TABLE(table1), 10);
	GLADE_HOOKUP_OBJECT(window1, table1, "table1");

	label1 = gtk_label_new(_("UID"));
	gtk_widget_show(label1);
	gtk_table_attach(GTK_TABLE(table1), label1, 0, 1, 0, 1,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_misc_set_alignment(GTK_MISC(label1), 0, 0.5);
	GLADE_HOOKUP_OBJECT(window1, label1, "label1");

	label2 = gtk_label_new(_("Name"));
	gtk_widget_show(label2);
	gtk_table_attach(GTK_TABLE(table1), label2, 0, 1, 1, 2,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_misc_set_alignment(GTK_MISC(label2), 0, 0.5);
	GLADE_HOOKUP_OBJECT(window1, label2, "label2");

	label3 = gtk_label_new(_("Insteon ID"));
	gtk_widget_show(label3);
	gtk_table_attach(GTK_TABLE(table1), label3, 0, 1, 2, 3,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_misc_set_alignment(GTK_MISC(label3), 0, 0.5);
	GLADE_HOOKUP_OBJECT(window1, label3, "label3");

	label4 = gtk_label_new(_("Device Type"));
	gtk_widget_show(label4);
	gtk_table_attach(GTK_TABLE(table1), label4, 0, 1, 3, 4,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_misc_set_alignment(GTK_MISC(label4), 0, 0.5);
	GLADE_HOOKUP_OBJECT(window1, label4, "label4");

	label5 = gtk_label_new(_("Device Catgegory"));
	gtk_widget_show(label5);
	gtk_table_attach(GTK_TABLE(table1), label5, 0, 1, 5, 6,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_misc_set_alignment(GTK_MISC(label5), 0, 0.5);
	GLADE_HOOKUP_OBJECT(window1, label5, "label5");

	label6 = gtk_label_new(_("Device Subcategory"));
	gtk_widget_show(label6);
	gtk_table_attach(GTK_TABLE(table1), label6, 0, 1, 6, 7,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_misc_set_alignment(GTK_MISC(label6), 0, 0.5);
	GLADE_HOOKUP_OBJECT(window1, label6, "label6");

	label7 = gtk_label_new(_("Device Firmware"));
	gtk_widget_show(label7);
	gtk_table_attach(GTK_TABLE(table1), label7, 0, 1, 7, 8,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_misc_set_alignment(GTK_MISC(label7), 0, 0.5);
	GLADE_HOOKUP_OBJECT(window1, label7, "label7");

	label8 = gtk_label_new(_("Protocol Version"));
	gtk_widget_show(label8);
	gtk_table_attach(GTK_TABLE(table1), label8, 0, 1, 8, 9,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_misc_set_alignment(GTK_MISC(label8), 0, 0.5);
	GLADE_HOOKUP_OBJECT(window1, label8, "label8");

	label9 = gtk_label_new(_("LED Brightness"));
	gtk_widget_show(label9);
	gtk_table_attach(GTK_TABLE(table1), label9, 0, 1, 9, 10,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_misc_set_alignment(GTK_MISC(label9), 0, 0.5);
	GLADE_HOOKUP_OBJECT(window1, label9, "label9");

	label10 = gtk_label_new(_("Ramp Rate"));
	gtk_widget_show(label10);
	gtk_table_attach(GTK_TABLE(table1), label10, 0, 1, 10, 11,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_misc_set_alignment(GTK_MISC(label10), 0, 0.5);
	GLADE_HOOKUP_OBJECT(window1, label10, "label10");

	entry_led = gtk_entry_new();
	gtk_widget_show(entry_led);
	gtk_table_attach(GTK_TABLE(table1), entry_led, 1, 2, 9, 10,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_editable_set_editable(GTK_EDITABLE(entry_led), FALSE);
	gtk_entry_set_invisible_char(GTK_ENTRY(entry_led), 9679);
	GLADE_HOOKUP_OBJECT(window1, entry_led, "entry_led");

	entry_ramp = gtk_entry_new();
	gtk_widget_show(entry_ramp);
	gtk_table_attach(GTK_TABLE(table1), entry_ramp, 1, 2, 10, 11,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_editable_set_editable(GTK_EDITABLE(entry_ramp), FALSE);
	gtk_entry_set_invisible_char(GTK_ENTRY(entry_ramp), 9679);
	GLADE_HOOKUP_OBJECT(window1, entry_ramp, "entry_ramp");

	button_get_ld = gtk_button_new_with_mnemonic(_("Get Link Data"));
	gtk_widget_show(button_get_ld);
	gtk_table_attach(GTK_TABLE(table1), button_get_ld, 1, 2, 11, 12,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	GLADE_HOOKUP_OBJECT(window1, button_get_ld, "button_get_ld");
	g_signal_connect(GTK_BUTTON(button_get_ld), "clicked",
			 G_CALLBACK(on_ld_activate),
			 (gpointer)devicelist_select);

	button_getinfo = gtk_button_new_with_mnemonic(_("Get Info"));
	gtk_widget_show(button_getinfo);
	gtk_table_attach(GTK_TABLE(table1), button_getinfo, 1, 2, 4, 5,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	GLADE_HOOKUP_OBJECT(window1, button_getinfo, "button_getinfo");
	g_signal_connect(GTK_BUTTON(button_getinfo), "clicked",
			 G_CALLBACK(on_getinfo_activate),
			 (gpointer)devicelist_select);

	spinner = gtk_spinner_new();
	gtk_widget_show(spinner);
	gtk_table_attach(GTK_TABLE(table1), spinner, 2, 3, 4, 5,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	GLADE_HOOKUP_OBJECT(window1, spinner, "spinner");

	entry_uid = gtk_entry_new();
	gtk_widget_show(entry_uid);
	gtk_table_attach(GTK_TABLE(table1), entry_uid, 1, 3, 0, 1,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_editable_set_editable(GTK_EDITABLE(entry_uid), FALSE);
	gtk_entry_set_invisible_char(GTK_ENTRY(entry_uid), 9679);
	GLADE_HOOKUP_OBJECT(window1, entry_uid, "entry_uid");

	entry_name = gtk_entry_new();
	gtk_widget_show(entry_name);
	gtk_table_attach(GTK_TABLE(table1), entry_name, 1, 3, 1, 2,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_editable_set_editable(GTK_EDITABLE(entry_name), FALSE);
	gtk_entry_set_invisible_char(GTK_ENTRY(entry_name), 9679);
	GLADE_HOOKUP_OBJECT(window1, entry_name, "entry_name");

	entry_id = gtk_entry_new();
	gtk_widget_show(entry_id);
	gtk_table_attach(GTK_TABLE(table1), entry_id, 1, 3, 2, 3,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_editable_set_editable(GTK_EDITABLE(entry_id), FALSE);
	gtk_entry_set_invisible_char(GTK_ENTRY(entry_id), 9679);
	GLADE_HOOKUP_OBJECT(window1, entry_id, "entry_id");

	entry_devtype = gtk_entry_new();
	gtk_widget_show(entry_devtype);
	gtk_table_attach(GTK_TABLE(table1), entry_devtype, 1, 3, 3, 4,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_editable_set_editable(GTK_EDITABLE(entry_devtype), FALSE);
	gtk_entry_set_invisible_char(GTK_ENTRY(entry_devtype), 9679);
	GLADE_HOOKUP_OBJECT(window1, entry_devtype, "entry_devtype");

	entry_devcat = gtk_entry_new();
	gtk_widget_show(entry_devcat);
	gtk_table_attach(GTK_TABLE(table1), entry_devcat, 1, 3, 5, 6,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_editable_set_editable(GTK_EDITABLE(entry_devcat), FALSE);
	gtk_entry_set_invisible_char(GTK_ENTRY(entry_devcat), 9679);
	GLADE_HOOKUP_OBJECT(window1, entry_devcat, "entry_devcat");

	entry_devsubcat = gtk_entry_new();
	gtk_widget_show(entry_devsubcat);
	gtk_table_attach(GTK_TABLE(table1), entry_devsubcat, 1, 3, 6, 7,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_editable_set_editable(GTK_EDITABLE(entry_devsubcat), FALSE);
	gtk_entry_set_invisible_char(GTK_ENTRY(entry_devsubcat), 9679);
	GLADE_HOOKUP_OBJECT(window1, entry_devsubcat, "entry_devsubcat");

	entry_devfw = gtk_entry_new();
	gtk_widget_show(entry_devfw);
	gtk_table_attach(GTK_TABLE(table1), entry_devfw, 1, 3, 7, 8,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_editable_set_editable(GTK_EDITABLE(entry_devfw), FALSE);
	gtk_entry_set_invisible_char(GTK_ENTRY(entry_devfw), 9679);
	GLADE_HOOKUP_OBJECT(window1, entry_devfw, "entry_devfw");

	entry_proto = gtk_entry_new();
	gtk_widget_show(entry_proto);
	gtk_table_attach(GTK_TABLE(table1), entry_proto, 1, 3, 8, 9,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_editable_set_editable(GTK_EDITABLE(entry_proto), FALSE);
	gtk_entry_set_invisible_char(GTK_ENTRY(entry_proto), 9679);
	GLADE_HOOKUP_OBJECT(window1, entry_proto, "entry_proto");

	scrolledwindow2 = gtk_scrolled_window_new(NULL, NULL);
	gtk_widget_show(scrolledwindow2);
	gtk_table_attach(GTK_TABLE(table1), scrolledwindow2, 0, 3, 12, 13,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(GTK_FILL), 0, 0);
	gtk_scrolled_window_set_shadow_type(GTK_SCROLLED_WINDOW(scrolledwindow2), GTK_SHADOW_IN);
	GLADE_HOOKUP_OBJECT(window1, scrolledwindow2, "scrolledwindow2");

	/* aldb code */
	aldb_model = create_aldb_model();
	aldblist = gtk_tree_view_new();
	setup_aldb_view(aldblist);
	gtk_tree_view_set_model(GTK_TREE_VIEW(aldblist),
				GTK_TREE_MODEL(aldb_model));
	gtk_widget_show(aldblist);
	GLADE_HOOKUP_OBJECT(window1, aldblist, "aldblist");
	gtk_container_add(GTK_CONTAINER(scrolledwindow2), aldblist);

	gtk_widget_size_request(aldblist, &size);
	gtk_widget_set_size_request(scrolledwindow2, size.width + 50,
				    size.height + 200);


	button_led_edit = gtk_button_new();
	gtk_widget_show(button_led_edit);
	gtk_table_attach(GTK_TABLE(table1), button_led_edit, 2, 3, 9, 10,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	GLADE_HOOKUP_OBJECT(window1, button_led_edit, "button_led_edit");

	alignment1 = gtk_alignment_new(0.5, 0.5, 0, 0);
	gtk_widget_show(alignment1);
	gtk_container_add(GTK_CONTAINER(button_led_edit), alignment1);
	GLADE_HOOKUP_OBJECT(window1, alignment1, "alignment1");

	hbox3 = gtk_hbox_new(FALSE, 2);
	gtk_widget_show(hbox3);
	gtk_container_add(GTK_CONTAINER(alignment1), hbox3);
	GLADE_HOOKUP_OBJECT(window1, hbox3, "hbox3");

	image1 = gtk_image_new_from_stock("gtk-edit", GTK_ICON_SIZE_BUTTON);
	gtk_widget_show(image1);
	gtk_box_pack_start(GTK_BOX(hbox3), image1, FALSE, FALSE, 0);
	GLADE_HOOKUP_OBJECT(window1, image1, "image1");

	label25 = gtk_label_new_with_mnemonic(_("Edit"));
	gtk_widget_show(label25);
	gtk_box_pack_start(GTK_BOX(hbox3), label25, FALSE, FALSE, 0);
	GLADE_HOOKUP_OBJECT(window1, label25, "label25");

	button_ramp_edit = gtk_button_new();
	gtk_widget_show(button_ramp_edit);
	gtk_table_attach(GTK_TABLE(table1), button_ramp_edit, 2, 3, 10, 11,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	GLADE_HOOKUP_OBJECT(window1, button_ramp_edit, "button_ramp_edit");

	alignment3 = gtk_alignment_new(0.5, 0.5, 0, 0);
	gtk_widget_show(alignment3);
	gtk_container_add(GTK_CONTAINER(button_ramp_edit), alignment3);
	GLADE_HOOKUP_OBJECT(window1, alignment3, "alignment3");

	hbox5 = gtk_hbox_new(FALSE, 2);
	gtk_widget_show(hbox5);
	gtk_container_add(GTK_CONTAINER(alignment3), hbox5);
	GLADE_HOOKUP_OBJECT(window1, hbox5, "hbox5");

	image3 = gtk_image_new_from_stock("gtk-edit", GTK_ICON_SIZE_BUTTON);
	gtk_widget_show(image3);
	gtk_box_pack_start(GTK_BOX(hbox5), image3, FALSE, FALSE, 0);
	GLADE_HOOKUP_OBJECT(window1, image3, "image3");

	label27 = gtk_label_new_with_mnemonic(_("Edit"));
	gtk_widget_show(label27);
	gtk_box_pack_start(GTK_BOX(hbox5), label27, FALSE, FALSE, 0);
	GLADE_HOOKUP_OBJECT(window1, label27, "label27");

	g_signal_connect((gpointer) new1, "activate",
			 G_CALLBACK(on_new1_activate),
			 NULL);
	g_signal_connect((gpointer) open1, "activate",
			 G_CALLBACK(on_open1_activate),
			 NULL);
	g_signal_connect((gpointer) save1, "activate",
			 G_CALLBACK(on_save1_activate),
			 NULL);
	g_signal_connect((gpointer) save_as1, "activate",
			 G_CALLBACK(on_save_as1_activate),
			 NULL);
	g_signal_connect((gpointer) quit1, "activate",
			 G_CALLBACK(on_quit1_activate),
			 NULL);
	g_signal_connect((gpointer) cut1, "activate",
			 G_CALLBACK(on_cut1_activate),
			 NULL);
	g_signal_connect((gpointer) copy1, "activate",
			 G_CALLBACK(on_copy1_activate),
			 NULL);
	g_signal_connect((gpointer) paste1, "activate",
			 G_CALLBACK(on_paste1_activate),
			 NULL);
	g_signal_connect((gpointer) delete1, "activate",
			 G_CALLBACK(on_delete1_activate),
			 NULL);
	g_signal_connect((gpointer) about1, "activate",
			 G_CALLBACK(on_about1_activate),
			 NULL);

	gtk_window_add_accel_group(GTK_WINDOW(window1), accel_group);

	return window1;
}

GtkWidget* create_dialog1(void)
{
	GtkWidget *dialog1;
	GtkWidget *dialog_vbox1;
	GtkWidget *table3;
	GtkWidget *label18;
	GtkWidget *label19;
	GtkWidget *label20;
	GtkWidget *label21;
	GtkWidget *label22;
	GtkWidget *label23;
	GtkWidget *label24;
	GtkWidget *checkbutton_editld_inuse;
	GtkWidget *checkbutton_editld_master;
	GtkWidget *entry_editld_group;
	GtkWidget *entry_editld_devid;
	GtkWidget *entry_editld_ld1;
	GtkWidget *entry_editld_ld2;
	GtkWidget *entry_editld_ld3;
	GtkWidget *dialog_action_area1;
	GtkWidget *cancelbutton1;
	GtkWidget *okbutton1;

	dialog1 = gtk_dialog_new();
	gtk_window_set_title(GTK_WINDOW(dialog1), _("dialog1"));
	gtk_window_set_type_hint(GTK_WINDOW(dialog1), GDK_WINDOW_TYPE_HINT_DIALOG);
	gtk_dialog_set_has_separator(GTK_DIALOG(dialog1), FALSE);

	dialog_vbox1 = GTK_DIALOG(dialog1)->vbox;
	gtk_widget_show(dialog_vbox1);

	table3 = gtk_table_new(7, 2, FALSE);
	gtk_widget_show(table3);
	gtk_box_pack_start(GTK_BOX(dialog_vbox1), table3, TRUE, TRUE, 0);
	gtk_table_set_row_spacings(GTK_TABLE(table3), 3);
	gtk_table_set_col_spacings(GTK_TABLE(table3), 3);

	label18 = gtk_label_new(_("Group #"));
	gtk_widget_show(label18);
	gtk_table_attach(GTK_TABLE(table3), label18, 0, 1, 0, 1,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_misc_set_alignment(GTK_MISC(label18), 0, 0.5);

	label19 = gtk_label_new(_("Device ID"));
	gtk_widget_show(label19);
	gtk_table_attach(GTK_TABLE(table3), label19, 0, 1, 1, 2,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_misc_set_alignment(GTK_MISC(label19), 0, 0.5);

	label20 = gtk_label_new(_("Link Data 1"));
	gtk_widget_show(label20);
	gtk_table_attach(GTK_TABLE(table3), label20, 0, 1, 2, 3,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_misc_set_alignment(GTK_MISC(label20), 0, 0.5);

	label21 = gtk_label_new(_("Link Data 2"));
	gtk_widget_show(label21);
	gtk_table_attach(GTK_TABLE(table3), label21, 0, 1, 3, 4,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_misc_set_alignment(GTK_MISC(label21), 0, 0.5);

	label22 = gtk_label_new(_("Link Data 3"));
	gtk_widget_show(label22);
	gtk_table_attach(GTK_TABLE(table3), label22, 0, 1, 4, 5,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_misc_set_alignment(GTK_MISC(label22), 0, 0.5);

	label23 = gtk_label_new(_("In Use"));
	gtk_widget_show(label23);
	gtk_table_attach(GTK_TABLE(table3), label23, 0, 1, 5, 6,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_misc_set_alignment(GTK_MISC(label23), 0, 0.5);

	label24 = gtk_label_new(_("Master"));
	gtk_widget_show(label24);
	gtk_table_attach(GTK_TABLE(table3), label24, 0, 1, 6, 7,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_misc_set_alignment(GTK_MISC(label24), 0, 0.5);

	checkbutton_editld_inuse = gtk_check_button_new_with_mnemonic("");
	gtk_widget_show(checkbutton_editld_inuse);
	gtk_table_attach(GTK_TABLE(table3), checkbutton_editld_inuse, 1, 2, 5, 6,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);

	checkbutton_editld_master = gtk_check_button_new_with_mnemonic("");
	gtk_widget_show(checkbutton_editld_master);
	gtk_table_attach(GTK_TABLE(table3), checkbutton_editld_master, 1, 2, 6, 7,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);

	entry_editld_group = gtk_entry_new();
	gtk_widget_show(entry_editld_group);
	gtk_table_attach(GTK_TABLE(table3), entry_editld_group, 1, 2, 0, 1,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_entry_set_invisible_char(GTK_ENTRY(entry_editld_group), 9679);

	entry_editld_devid = gtk_entry_new();
	gtk_widget_show(entry_editld_devid);
	gtk_table_attach(GTK_TABLE(table3), entry_editld_devid, 1, 2, 1, 2,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_entry_set_invisible_char(GTK_ENTRY(entry_editld_devid), 9679);

	entry_editld_ld1 = gtk_entry_new();
	gtk_widget_show(entry_editld_ld1);
	gtk_table_attach(GTK_TABLE(table3), entry_editld_ld1, 1, 2, 2, 3,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_entry_set_invisible_char(GTK_ENTRY(entry_editld_ld1), 9679);

	entry_editld_ld2 = gtk_entry_new();
	gtk_widget_show(entry_editld_ld2);
	gtk_table_attach(GTK_TABLE(table3), entry_editld_ld2, 1, 2, 3, 4,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_entry_set_invisible_char(GTK_ENTRY(entry_editld_ld2), 9679);

	entry_editld_ld3 = gtk_entry_new();
	gtk_widget_show(entry_editld_ld3);
	gtk_table_attach(GTK_TABLE(table3), entry_editld_ld3, 1, 2, 4, 5,
			 (GtkAttachOptions)(GTK_FILL),
			 (GtkAttachOptions)(0), 0, 0);
	gtk_entry_set_invisible_char(GTK_ENTRY(entry_editld_ld3), 9679);

	dialog_action_area1 = GTK_DIALOG(dialog1)->action_area;
	gtk_widget_show(dialog_action_area1);
	gtk_button_box_set_layout(GTK_BUTTON_BOX(dialog_action_area1), GTK_BUTTONBOX_END);

	cancelbutton1 = gtk_button_new_from_stock("gtk-cancel");
	gtk_widget_show(cancelbutton1);
	gtk_dialog_add_action_widget(GTK_DIALOG(dialog1), cancelbutton1, GTK_RESPONSE_CANCEL);
	GTK_WIDGET_SET_FLAGS(cancelbutton1, GTK_CAN_DEFAULT);

	okbutton1 = gtk_button_new_from_stock("gtk-ok");
	gtk_widget_show(okbutton1);
	gtk_dialog_add_action_widget(GTK_DIALOG(dialog1), okbutton1, GTK_RESPONSE_OK);
	GTK_WIDGET_SET_FLAGS(okbutton1, GTK_CAN_DEFAULT);

	/* Store pointers to all widgets, for use by lookup_widget(). */
	GLADE_HOOKUP_OBJECT_NO_REF(dialog1, dialog1, "dialog1");
	GLADE_HOOKUP_OBJECT_NO_REF(dialog1, dialog_vbox1, "dialog_vbox1");
	GLADE_HOOKUP_OBJECT(dialog1, table3, "table3");
	GLADE_HOOKUP_OBJECT(dialog1, label18, "label18");
	GLADE_HOOKUP_OBJECT(dialog1, label19, "label19");
	GLADE_HOOKUP_OBJECT(dialog1, label20, "label20");
	GLADE_HOOKUP_OBJECT(dialog1, label21, "label21");
	GLADE_HOOKUP_OBJECT(dialog1, label22, "label22");
	GLADE_HOOKUP_OBJECT(dialog1, label23, "label23");
	GLADE_HOOKUP_OBJECT(dialog1, label24, "label24");
	GLADE_HOOKUP_OBJECT(dialog1, checkbutton_editld_inuse, "checkbutton_editld_inuse");
	GLADE_HOOKUP_OBJECT(dialog1, checkbutton_editld_master, "checkbutton_editld_master");
	GLADE_HOOKUP_OBJECT(dialog1, entry_editld_group, "entry_editld_group");
	GLADE_HOOKUP_OBJECT(dialog1, entry_editld_devid, "entry_editld_devid");
	GLADE_HOOKUP_OBJECT(dialog1, entry_editld_ld1, "entry_editld_ld1");
	GLADE_HOOKUP_OBJECT(dialog1, entry_editld_ld2, "entry_editld_ld2");
	GLADE_HOOKUP_OBJECT(dialog1, entry_editld_ld3, "entry_editld_ld3");
	GLADE_HOOKUP_OBJECT_NO_REF(dialog1, dialog_action_area1, "dialog_action_area1");
	GLADE_HOOKUP_OBJECT(dialog1, cancelbutton1, "cancelbutton1");
	GLADE_HOOKUP_OBJECT(dialog1, okbutton1, "okbutton1");

	return dialog1;
}

GtkWidget* create_aboutdialog1(void)
{
	GtkWidget *aboutdialog1;
	/* TRANSLATORS: Replace this string with your names, one name per line. */
	gchar *translators = _("translator-credits");

	aboutdialog1 = gtk_about_dialog_new();
	gtk_container_set_border_width(GTK_CONTAINER(aboutdialog1), 5);
	gtk_about_dialog_set_version(GTK_ABOUT_DIALOG(aboutdialog1), VERSION);
	gtk_about_dialog_set_name(GTK_ABOUT_DIALOG(aboutdialog1), _("Project5"));
	gtk_about_dialog_set_translator_credits(GTK_ABOUT_DIALOG(aboutdialog1), translators);

	/* Store pointers to all widgets, for use by lookup_widget(). */
	GLADE_HOOKUP_OBJECT_NO_REF(aboutdialog1, aboutdialog1, "aboutdialog1");

	return aboutdialog1;
}

